library(raster)
library(RStoolbox)
setwd("C:/Users/Rob/Desktop/UNIBO_05.04.21/Telerilevamento e GIS/lab")
so <- brick("Solar_Orbiter_s_first_views_of_the_Sun_pillars.jpg")
# i valori di so vanno da 0 a 255. Essendo un'immagine a 8 bit, ho 2^8 valori compresi fra 0 e 255
plotRGB(so, 1, 2, 3, stretch = 'lin')
# CLASSIFICAZIONE NON SUPERVISIONATA (il training set non viene definite a monte, ma viene determinato con campionamento random)
# NB. siccome il campionamento per il training set è random, i risultati variano leggermente fra i dispositivi (a meno che non si impostino i seeds con set.seed())
soc <- unsuperClass(so, nClasses = 30) # soc contiene un'analisi (model) e una mappa (map)
plot(soc$map)
