library(raster)
library(RStoolbox)
setwd("C:/Users/Rob/Desktop/UNIBO_05.04.21/Telerilevamento e GIS/lab")
# Sun (source: https://www.esa.int/ESA_Multimedia/Missions/Solar_Orbiter/(result_type)/images)
# 8 bit images (2^8 = 256 values per pixel)
so <- brick("Solar_Orbiter_s_first_views_of_the_Sun_pillars.jpg")
plotRGB(so, 1, 2, 3, stretch = 'lin')
# UNSUPERVISED CLASSIFICATION (random sampling for the definition of training set)
# set.seed() for coherent results using different machines)
soc <- unsuperClass(so, nClasses = 30) # soc consist in a 'model' and a 'map'
plot(soc$map)
#
# Grand Canyon (Landsat)
gc <- brick("dolansprings_oli_2013088_canyon_lrg.jpg")
plotRGB(gc, stretch = "hist")
gcc <- unsuperClass(gc, nClasses = 5)
plot(gcc$map)
